# Optimized for MAC (contact: vijayendrap@gmail.com)

$master_ip = "10.245.20.50"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "#{$master_ip}", netmask: "255.255.255.0", nic_type: "virtio", dhcp_enabled: false
  config.vm.network "public_network", bridge: "en0"
  config.vm.define "jenkins" do |jenkins|
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = "1024"
      # v.name = "Jenkins Server"
      v.customize "pre-boot", [
            "storageattach", :id,
            "--storagectl", "IDE",
             "--port", "1",
            "--device", "0",
            "--type", "dvddrive",
            "--medium", "emptydrive",
            ]
      v.customize ["modifyvm", :id, "--clipboard",   "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    jenkins.vm.network "forwarded_port", guest: 8080, host: 8082

    jenkins.vm.provision "shell", path: "scripts/01--commons.sh"
    jenkins.vm.provision "shell", path: "scripts/02--jdk8.sh"
    jenkins.vm.provision "shell", path: "scripts/03--jenkins.sh"
    jenkins.vm.provision "shell", path: "scripts/04--docker.sh"
    jenkins.vm.provision "shell", path: "scripts/05--kube.sh"
  end
  config.vm.synced_folder "/tmp/kube/", "/home/vagrant/kube/", type: "rsync", owner: "root", group: "root"
end
